-- RedefineTable: reshape RaekwonLead's columns (rename role->roleTitle,
-- url->sourceUrl, rationale->explanation, compensation->salaryOrRate; drop
-- sourceLabel; add required keyword + rank, backfilling keyword from the
-- parent report and rank from each lead's original insertion order) and add
-- the nullable duplicateVariantsSuppressed column. Hand-written (not
-- generated by `prisma migrate dev`) so existing RaekwonLead rows are
-- preserved via backfill instead of being dropped.
PRAGMA defer_foreign_keys=ON;
PRAGMA foreign_keys=OFF;
CREATE TABLE "new_RaekwonLead" (
    "id" TEXT NOT NULL PRIMARY KEY,
    "reportId" TEXT NOT NULL,
    "company" TEXT NOT NULL,
    "roleTitle" TEXT NOT NULL,
    "jobType" TEXT NOT NULL,
    "location" TEXT,
    "keyword" TEXT NOT NULL,
    "salaryOrRate" TEXT,
    "rank" INTEGER NOT NULL,
    "explanation" TEXT NOT NULL,
    "sourceUrl" TEXT NOT NULL,
    "duplicateVariantsSuppressed" TEXT,
    "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT "RaekwonLead_reportId_fkey" FOREIGN KEY ("reportId") REFERENCES "RaekwonReport" ("id") ON DELETE CASCADE ON UPDATE CASCADE
);
INSERT INTO "new_RaekwonLead" ("id", "reportId", "company", "roleTitle", "jobType", "location", "keyword", "salaryOrRate", "rank", "explanation", "sourceUrl", "duplicateVariantsSuppressed", "createdAt")
SELECT
  "l"."id",
  "l"."reportId",
  "l"."company",
  "l"."role",
  "l"."jobType",
  "l"."location",
  (SELECT "r"."keyword" FROM "RaekwonReport" "r" WHERE "r"."id" = "l"."reportId"),
  "l"."compensation",
  (SELECT COUNT(*) FROM "RaekwonLead" "earlier" WHERE "earlier"."reportId" = "l"."reportId" AND "earlier"."rowid" <= "l"."rowid"),
  "l"."rationale",
  "l"."url",
  NULL,
  "l"."createdAt"
FROM "RaekwonLead" "l";
DROP TABLE "RaekwonLead";
ALTER TABLE "new_RaekwonLead" RENAME TO "RaekwonLead";
CREATE INDEX "RaekwonLead_reportId_rank_idx" ON "RaekwonLead"("reportId", "rank");
PRAGMA foreign_keys=ON;
PRAGMA defer_foreign_keys=OFF;
